### ISSUE TITLE
when executing the command python run.py 

### ISSUE THREAD

**Issue by Toshik-One** [xtekky/chatgpt-clone#59]
when executing the command python run.py 
gives an error message :
Traceback (most recent call last):
  File "C:\chatgpt-clone\run.py", line 19, in <module>
    backend_api  = Backend_Api(app, config)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\chatgpt-clone\server\backend.py", line 17, in __init__
    self.openai_key = os.environ["OPENAI_API_KEY"] or config['openai_key']
                      ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'OPENAI_API_KEY'

What should I do ?
API_KEY I entered in the file config.json

**Comment by KaarisMoiLeCrane** [comment]
Hello, I encountered the same problem while using Docker. To fix it, you can remove both instances of `os.environ` in `server/backend.py` line 17 and 18 (as well as the `or` keyword). This should resolve the issue.

If you're still experiencing issues, try replacing `os.environ["OPENAI_API_KEY"] or config['openai_key']` with your own OpenAI API key enclosed in quotation marks, like this: "sk-...".
Similarly, replace `os.environ["OPENAI_API_BASE"] or config['openai_api_base']` with the base API URL enclosed in quotation marks, like this: "https://api.openai.com".

I'm posting this right now, but after two hours, I believe that you have successfully found a fix for the issue.
I hope this will be helpful for you and anyone else who encounters this issue in the future.

**Comment by dvelm** [comment]
the UI is loaded but typing a message gives {"_action":"_ask","error":"an error occurred string indices must be integers","success":false}

**Comment by Shivak11** [comment]
> 

Same here: I am also getting the same error  {"_action":"_ask","error":"an error occurred 'Backend_Api' object has no attribute 'openai_api_base'","success":false}

**Comment by jackmingo** [comment]
Pull request: https://github.com/xtekky/chatgpt-clone/pull/63 should fixt this.

**Comment by jackmingo** [comment]
Closed my pull request,  This one will resolve it: https://github.com/xtekky/chatgpt-clone/pull/57

**Comment by dvelm** [comment]
which key? How to resolve this?

**Comment by jackmingo** [comment]
See my comment 3 notes up.  Set the env vars for OPENAI_API_KEY and OPENAI_API_BASE.  Once pull #57 is brought in, you won't need to do that and can set via the config file.

**Comment by Toshik-One** [comment]
> Hello, I encountered the same problem while using Docker. To fix it, you can remove both instances of `os.environ` in `server/backend.py` line 17 and 18 (as well as the `or` keyword). This should resolve the issue.
> 
> If you're still experiencing issues, try replacing `os.environ["OPENAI_API_KEY"] or config['openai_key']` with your own OpenAI API key enclosed in quotation marks, like this: "sk-...". Similarly, replace `os.environ["OPENAI_API_BASE"] or config['openai_api_base']` with the base API URL enclosed in quotation marks, like this: "https://api.openai.com".
> 
> I'm posting this right now, but after two hours, I believe that you have successfully found a fix for the issue. I hope this will be helpful for you and anyone else who encounters this issue in the future.

did as you suggested to me, everything started up, but when you enter a word, nothing happens, but in the console it displays this
list index out of range
None
list index out of range
None
list index out of range
None
list index out of range
None
list index out of range
None
list index out of range
None
list index out of range
None
list index out of range
None
192.168.229.70 - - [28/Apr/2023 21:48:59] "POST /backend-api/v2/conversation HTTP/1.1" 200 -

**Comment by dvelm** [comment]
I have no key for OPENAI_API_KEY .  There should a clearer guide

**Comment by KaarisMoiLeCrane** [comment]
> I have no key for OPENAI_API_KEY . There should a clearer guide

Hello, to obtain an **OpenAI API key**, it's a very easy process. First, navigate to [https://platform.openai.com/](https://platform.openai.com/) and log in if needed. Then, click on your profile located at the **top right corner** of the page, and select **View API keys**.
From there, click on the **+ Create new secret key** button in the center of the page, give it a name that will help you remember its purpose, and **copy the key**. 
The copied **API key** should begin with "**sk-**". Remember to keep this **key private** and **never share** it with others.

If you're **unable to locate** the **+ Create new secret key** button, try clicking on the **API keys** section in the left-hand navigation bar (under the "USER" text). From there, you should be able to create a new key by following the steps outlined earlier.

I hope this will be helpful for you.

**Comment by KaarisMoiLeCrane** [comment]
> > Hello, I encountered the same problem while using Docker. To fix it, you can remove both instances of `os.environ` in `server/backend.py` line 17 and 18 (as well as the `or` keyword). This should resolve the issue.
> > If you're still experiencing issues, try replacing `os.environ["OPENAI_API_KEY"] or config['openai_key']` with your own OpenAI API key enclosed in quotation marks, like this: "sk-...". Similarly, replace `os.environ["OPENAI_API_BASE"] or config['openai_api_base']` with the base API URL enclosed in quotation marks, like this: "https://api.openai.com".
> > I'm posting this right now, but after two hours, I believe that you have successfully found a fix for the issue. I hope this will be helpful for you and anyone else who encounters this issue in the future.
> 
> did as you suggested to me, everything started up, but when you enter a word, nothing happens, but in the console it displays this list index out of range None list index out of range None list index out of range None list index out of range None list index out of range None list index out of range None list index out of range None list index out of range None 192.168.229.70 - - [28/Apr/2023 21:48:59] "POST /backend-api/v2/conversation HTTP/1.1" 200 -

Hello, I'm sorry to hear that you're experiencing this error, but I have not encountered it before so I don't have any idea about how to fix this.
